location / {
    root __INSTALL_DIR__/public;
    try_files $uri $uri/ /index.php?$query_string;
    index index.html index.htm index.php;
}


location ~ \.php$ {
    root __INSTALL_DIR__/public;
    index index.html index.htm index.php;
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    include fastcgi_params;
}

location ~ /\.(?!well-known).* {
    deny all;
}

